# Generated by Django 4.2 on 2023-05-28 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=150, null=True)),
                ('em_fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship', models.CharField(blank=True, max_length=150, null=True)),
                ('em_contactno', models.BigIntegerField(blank=True, null=True)),
                ('em_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('renew', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ss_email', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('payment', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('renew_price', models.IntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_email', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user_monthly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=150, null=True)),
                ('em_fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship', models.CharField(blank=True, max_length=150, null=True)),
                ('em_contactno', models.BigIntegerField(blank=True, null=True)),
                ('em_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('renew', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ss_email', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('payment', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('renew_startdate', models.DateField(blank=True, null=True)),
                ('renew_enddate', models.DateField(blank=True, null=True)),
                ('renew_price', models.IntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_email', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user_custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=150, null=True)),
                ('em_fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship', models.CharField(blank=True, max_length=150, null=True)),
                ('em_contactno', models.BigIntegerField(blank=True, null=True)),
                ('em_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('renew', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ss_email', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('payment', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('renew_price', models.IntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_email', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user_annual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
